/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator.expressions;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link itu.xtext.landin.configurator.expressions.Expression#getLeft <em>Left</em>}</li>
 *   <li>{@link itu.xtext.landin.configurator.expressions.Expression#getOperation <em>Operation</em>}</li>
 *   <li>{@link itu.xtext.landin.configurator.expressions.Expression#getRight <em>Right</em>}</li>
 *   <li>{@link itu.xtext.landin.configurator.expressions.Expression#getParanthesis <em>Paranthesis</em>}</li>
 *   <li>{@link itu.xtext.landin.configurator.expressions.Expression#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see itu.xtext.landin.configurator.expressions.ExpressionsPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Expression)
   * @see itu.xtext.landin.configurator.expressions.ExpressionsPackage#getExpression_Left()
   * @model containment="true"
   * @generated
   */
  Expression getLeft();

  /**
   * Sets the value of the '{@link itu.xtext.landin.configurator.expressions.Expression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Expression value);

  /**
   * Returns the value of the '<em><b>Operation</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operation</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' attribute list.
   * @see itu.xtext.landin.configurator.expressions.ExpressionsPackage#getExpression_Operation()
   * @model unique="false"
   * @generated
   */
  EList<String> getOperation();

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link itu.xtext.landin.configurator.expressions.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see itu.xtext.landin.configurator.expressions.ExpressionsPackage#getExpression_Right()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getRight();

  /**
   * Returns the value of the '<em><b>Paranthesis</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Paranthesis</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paranthesis</em>' containment reference.
   * @see #setParanthesis(Expression)
   * @see itu.xtext.landin.configurator.expressions.ExpressionsPackage#getExpression_Paranthesis()
   * @model containment="true"
   * @generated
   */
  Expression getParanthesis();

  /**
   * Sets the value of the '{@link itu.xtext.landin.configurator.expressions.Expression#getParanthesis <em>Paranthesis</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Paranthesis</em>' containment reference.
   * @see #getParanthesis()
   * @generated
   */
  void setParanthesis(Expression value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see itu.xtext.landin.configurator.expressions.ExpressionsPackage#getExpression_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link itu.xtext.landin.configurator.expressions.Expression#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Expression
