/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator.expressions;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Free Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link itu.xtext.landin.configurator.expressions.FreeText#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see itu.xtext.landin.configurator.expressions.ExpressionsPackage#getFreeText()
 * @model
 * @generated
 */
public interface FreeText extends Title
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see itu.xtext.landin.configurator.expressions.ExpressionsPackage#getFreeText_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link itu.xtext.landin.configurator.expressions.FreeText#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // FreeText
