/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator.expressions;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Title</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see itu.xtext.landin.configurator.expressions.ExpressionsPackage#getTitle()
 * @model
 * @generated
 */
public interface Title extends EObject
{
} // Title
