/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator.ui.contentassist;

import itu.xtext.landin.configurator.ui.contentassist.AbstractExpressionsProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {
}
