/*
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator.parser.antlr;

import com.google.inject.Inject;
import itu.xtext.landin.configurator.parser.antlr.internal.InternalExpressionsParser;
import itu.xtext.landin.configurator.services.ExpressionsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ExpressionsParser extends AbstractAntlrParser {

	@Inject
	private ExpressionsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalExpressionsParser createParser(XtextTokenStream stream) {
		return new InternalExpressionsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ExpressionsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExpressionsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
