/*
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ExpressionsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("itu/xtext/landin/configurator/parser/antlr/internal/InternalExpressions.tokens");
	}
}
