/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator;

import itu.xtext.landin.configurator.ExpressionsStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExpressionsStandaloneSetup extends ExpressionsStandaloneSetupGenerated {
  public static void doSetup() {
    ExpressionsStandaloneSetup _expressionsStandaloneSetup = new ExpressionsStandaloneSetup();
    _expressionsStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
