/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator;

import itu.xtext.landin.configurator.AbstractExpressionsRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExpressionsRuntimeModule extends AbstractExpressionsRuntimeModule {
}
