/*
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ExpressionsRuntimeModule extends AbstractExpressionsRuntimeModule {
}
