/*
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExpressionsScopeProvider extends DelegatingScopeProvider {
}
