/**
 * generated by Xtext 2.10.0
 */
package itu.xtext.landin.configurator.ui;

import itu.xtext.landin.configurator.ui.AbstractExpressionsUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ExpressionsUiModule extends AbstractExpressionsUiModule {
  public ExpressionsUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
